version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false --ISCAgent false
    restart: always
    ports: 
      - 51773:1972
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
